### ISSUE TITLE
0.10.2.2: `make check` fails in `test/bitcoin-util-test.py`

### ISSUE THREAD

**Issue by onlyjob** [litecoin-project/litecoin#207]
0.10.2.2: `make check` fails in `test/bitcoin-util-test.py` on x86_64 (Debian).
`src/test/bitcoin-util-test.py.log` contains the following:

~~~~
Traceback (most recent call last):
  File "./test/bitcoin-util-test.py", line 12, in <module>
    "bitcoin-util-test.json",buildenv)
  File "/mnt/tmpssd/src/litecoin/litecoin-0.10.2.2/src/test/bctest.py", line 51, in bctester
    bctest(testDir, testObj, buildenv.exeext)
  File "/mnt/tmpssd/src/litecoin/litecoin-0.10.2.2/src/test/bctest.py", line 27, in bctest
    proc = subprocess.Popen(execrun, stdin=stdinCfg, stdout=subprocess.PIPE, stderr=subprocess.PIPE,universal_newlines=True)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
~~~~

**Comment by thrasher-** [comment]
Thanks for the reporting this, the issue should be fixed now. Please perform a git pull and try to do a make check again.

**Comment by onlyjob** [comment]
Thank you for quick fix. `git pull` is a bit harsh but I applied e5bd36a on top of 0.10.2.2 and it fixed the problem. Well done. :)

**Comment by thrasher-** [comment]
Great to here its all fixed. I'll close this issue now.
