### ISSUE TITLE
ImportError: No module named 'litecoin_scrypt'

### ISSUE THREAD

**Issue by cryptozeny** [litecoin-project/litecoin#582]
I got error when I run `test_runner.py`

```bash
$ ./test/functional/test_runner.py 
Temporary test directory at /tmp/litecoin_test_runner_20190219_033151

feature_block.py failed, Duration: 0 s

stdout:


stderr:
Traceback (most recent call last):
  File "/home/ak/git/TEST-OTHER-COIN/litecoin/test/functional/feature_block.py", line 16, in <module>
    from test_framework.comptool import TestManager, TestInstance, RejectResult
  File "/home/ak/git/TEST-OTHER-COIN/litecoin/test/functional/test_framework/comptool.py", line 20, in <module>
    from .mininode import *
  File "/home/ak/git/TEST-OTHER-COIN/litecoin/test/functional/test_framework/mininode.py", line 23, in <module>
    from test_framework.messages import *
  File "/home/ak/git/TEST-OTHER-COIN/litecoin/test/functional/test_framework/messages.py", line 26, in <module>
    import litecoin_scrypt
ImportError: No module named 'litecoin_scrypt'
```

How to install `litecoin_scrypt` on linux?

**Comment by thrasher-** [comment]
You'll need to install it via pip `pip3 install litecoin_scrypt`

**Comment by cryptozeny** [comment]
thanks! it works on ubuntu 16.04

```
sudo apt-get install python3-pip
pip3 install litecoin_scrypt
```

result
```
$ ./test/functional/test_runner.py 
Temporary test directory at /tmp/litecoin_test_runner_20190219_141153
.................................................
rpc_fundrawtransaction.py passed, Duration: 25 s
.....................
wallet_hd.py passed, Duration: 36 s
............................
p2p_compactblocks.py passed, Duration: 25 s
...........
feature_segwit.py passed, Duration: 20 s
............
wallet_accounts.py passed, Duration: 6 s
......................
wallet_basic.py passed, Duration: 24 s
...........
wallet_dump.py passed, Duration: 6 s
.......
rpc_listtransactions.py passed, Duration: 4 s
....
wallet_backup.py passed, Duration: 87 s
.......
wallet_zapwallettxes.py passed, Duration: 4 s
.......
p2p_sendheaders.py passed, Duration: 10 s
...
wallet_importmulti.py passed, Duration: 6 s
......
rpc_txoutproof.py passed, Duration: 3 s

mempool_limit.py passed, Duration: 6 s
...........
wallet_listreceivedby.py passed, Duration: 6 s
...
wallet_abandonconflict.py passed, Duration: 8 s
....................
rpc_rawtransaction.py passed, Duration: 10 s
..........
feature_csv_activation.py passed, Duration: 18 s
........
feature_reindex.py passed, Duration: 4 s
.............
wallet_keypool_topup.py passed, Duration: 7 s
.........
interface_zmq.py passed, Duration: 5 s
..
interface_bitcoin_cli.py passed, Duration: 1 s
..
mempool_resurrect.py passed, Duration: 1 s
...
p2p_segwit.py passed, Duration: 83 s

wallet_txn_doublespend.py --mineblock passed, Duration: 2 s
..
wallet_txn_clone.py passed, Duration: 2 s

wallet_txn_clone.py --segwit passed, Duration: 2 s
...
rpc_getchaintips.py passed, Duration: 2 s
.
mempool_spend_coinbase.py passed, Duration: 1 s
.....
interface_rest.py passed, Duration: 6 s

mempool_reorg.py passed, Duration: 3 s
...........
wallet_address_types.py passed, Duration: 42 s

mempool_persist.py passed, Duration: 7 s
..
wallet_multiwallet.py passed, Duration: 8 s

interface_http.py passed, Duration: 2 s
...
feature_proxy.py passed, Duration: 2 s

rpc_users.py passed, Duration: 3 s

rpc_signrawtransaction.py passed, Duration: 1 s
.
rpc_decodescript.py passed, Duration: 1 s

p2p_disconnect_ban.py passed, Duration: 2 s
..
rpc_deprecated.py passed, Duration: 1 s
.
wallet_multiwallet.py --usecli passed, Duration: 9 s

wallet_disable.py passed, Duration: 1 s
.
rpc_net.py passed, Duration: 1 s
.
p2p_mempool.py passed, Duration: 1 s
...
wallet_keypool.py passed, Duration: 4 s

rpc_blockchain.py passed, Duration: 8 s
...
p2p_invalid_block.py passed, Duration: 2 s

p2p_invalid_tx.py passed, Duration: 2 s
...
mining_prioritisetransaction.py passed, Duration: 7 s

rpc_preciousblock.py passed, Duration: 2 s
.
rpc_signmessage.py passed, Duration: 1 s
..
feature_versionbits_warning.py passed, Duration: 5 s

wallet_importprunedfunds.py passed, Duration: 3 s
....
feature_nulldummy.py passed, Duration: 4 s

mining_basic.py passed, Duration: 3 s
.
wallet_bumpfee.py skipped

rpc_named_arguments.py passed, Duration: 1 s
.......
wallet_listsinceblock.py passed, Duration: 4 s
..
wallet_import_rescan.py passed, Duration: 10 s
.
p2p_leak.py passed, Duration: 6 s
.....
wallet_scriptaddress2.py passed, Duration: 4 s

wallet_encryption.py passed, Duration: 6 s
..
rpc_uptime.py passed, Duration: 1 s
..
wallet_resendwallettransactions.py passed, Duration: 1 s
........
feature_dersig.py passed, Duration: 11 s
.
feature_minchainwork.py passed, Duration: 5 s
...
feature_cltv.py passed, Duration: 11 s
.
feature_uacomment.py passed, Duration: 3 s
.....
feature_logging.py passed, Duration: 3 s
.
p2p_fingerprint.py passed, Duration: 8 s

p2p_unrequested_blocks.py passed, Duration: 5 s

feature_help.py passed, Duration: 0 s

p2p_node_network_limited.py passed, Duration: 2 s

feature_block.py passed, Duration: 216 s

feature_config_args.py passed, Duration: 2 s

TEST                                  | STATUS    | DURATION

feature_block.py                      | ✓ Passed  | 216 s
feature_cltv.py                       | ✓ Passed  | 11 s
feature_config_args.py                | ✓ Passed  | 2 s
feature_csv_activation.py             | ✓ Passed  | 18 s
feature_dersig.py                     | ✓ Passed  | 11 s
feature_help.py                       | ✓ Passed  | 0 s
feature_logging.py                    | ✓ Passed  | 3 s
feature_minchainwork.py               | ✓ Passed  | 5 s
feature_nulldummy.py                  | ✓ Passed  | 4 s
feature_proxy.py                      | ✓ Passed  | 2 s
feature_reindex.py                    | ✓ Passed  | 4 s
feature_segwit.py                     | ✓ Passed  | 20 s
feature_uacomment.py                  | ✓ Passed  | 3 s
feature_versionbits_warning.py        | ✓ Passed  | 5 s
interface_bitcoin_cli.py              | ✓ Passed  | 1 s
interface_http.py                     | ✓ Passed  | 2 s
interface_rest.py                     | ✓ Passed  | 6 s
interface_zmq.py                      | ✓ Passed  | 5 s
mempool_limit.py                      | ✓ Passed  | 6 s
mempool_persist.py                    | ✓ Passed  | 7 s
mempool_reorg.py                      | ✓ Passed  | 3 s
mempool_resurrect.py                  | ✓ Passed  | 1 s
mempool_spend_coinbase.py             | ✓ Passed  | 1 s
mining_basic.py                       | ✓ Passed  | 3 s
mining_prioritisetransaction.py       | ✓ Passed  | 7 s
p2p_compactblocks.py                  | ✓ Passed  | 25 s
p2p_disconnect_ban.py                 | ✓ Passed  | 2 s
p2p_fingerprint.py                    | ✓ Passed  | 8 s
p2p_invalid_block.py                  | ✓ Passed  | 2 s
p2p_invalid_tx.py                     | ✓ Passed  | 2 s
p2p_leak.py                           | ✓ Passed  | 6 s
p2p_mempool.py                        | ✓ Passed  | 1 s
p2p_node_network_limited.py           | ✓ Passed  | 2 s
p2p_segwit.py                         | ✓ Passed  | 83 s
p2p_sendheaders.py                    | ✓ Passed  | 10 s
p2p_unrequested_blocks.py             | ✓ Passed  | 5 s
rpc_blockchain.py                     | ✓ Passed  | 8 s
rpc_decodescript.py                   | ✓ Passed  | 1 s
rpc_deprecated.py                     | ✓ Passed  | 1 s
rpc_fundrawtransaction.py             | ✓ Passed  | 25 s
rpc_getchaintips.py                   | ✓ Passed  | 2 s
rpc_listtransactions.py               | ✓ Passed  | 4 s
rpc_named_arguments.py                | ✓ Passed  | 1 s
rpc_net.py                            | ✓ Passed  | 1 s
rpc_preciousblock.py                  | ✓ Passed  | 2 s
rpc_rawtransaction.py                 | ✓ Passed  | 10 s
rpc_signmessage.py                    | ✓ Passed  | 1 s
rpc_signrawtransaction.py             | ✓ Passed  | 1 s
rpc_txoutproof.py                     | ✓ Passed  | 3 s
rpc_uptime.py                         | ✓ Passed  | 1 s
rpc_users.py                          | ✓ Passed  | 3 s
wallet_abandonconflict.py             | ✓ Passed  | 8 s
wallet_accounts.py                    | ✓ Passed  | 6 s
wallet_address_types.py               | ✓ Passed  | 42 s
wallet_backup.py                      | ✓ Passed  | 87 s
wallet_basic.py                       | ✓ Passed  | 24 s
wallet_bumpfee.py                     | ○ Skipped | 1 s
wallet_disable.py                     | ✓ Passed  | 1 s
wallet_dump.py                        | ✓ Passed  | 6 s
wallet_encryption.py                  | ✓ Passed  | 6 s
wallet_hd.py                          | ✓ Passed  | 36 s
wallet_import_rescan.py               | ✓ Passed  | 10 s
wallet_importmulti.py                 | ✓ Passed  | 6 s
wallet_importprunedfunds.py           | ✓ Passed  | 3 s
wallet_keypool.py                     | ✓ Passed  | 4 s
wallet_keypool_topup.py               | ✓ Passed  | 7 s
wallet_listreceivedby.py              | ✓ Passed  | 6 s
wallet_listsinceblock.py              | ✓ Passed  | 4 s
wallet_multiwallet.py                 | ✓ Passed  | 8 s
wallet_multiwallet.py --usecli        | ✓ Passed  | 9 s
wallet_resendwallettransactions.py    | ✓ Passed  | 1 s
wallet_scriptaddress2.py              | ✓ Passed  | 4 s
wallet_txn_clone.py                   | ✓ Passed  | 2 s
wallet_txn_clone.py --segwit          | ✓ Passed  | 2 s
wallet_txn_doublespend.py --mineblock | ✓ Passed  | 2 s
wallet_zapwallettxes.py               | ✓ Passed  | 4 s

ALL                                   | ✓ Passed  | 845 s (accumulated) 
Runtime: 217 s
$
```

**Comment by cryptozeny** [comment]
but why it skipped?

```
wallet_bumpfee.py                     | ○ Skipped | 1 s
```

**Comment by losh11** [comment]
`wallet_bumpfee.py` is a test for RBF, which is not supported by Litecoin. So we skip that test.

**Comment by cryptozeny** [comment]
thanks for quick response :+1: 

closing
